from __future__ import annotations

from typing import Protocol
import numpy as np
from .types import Detection, EnrollmentSample, Identity, ModelSpec


class FaceBackend(Protocol):
    model: ModelSpec

    def detect(self, image_bgr: np.ndarray, *, max_faces: int | None = None,
               central_only: bool = False) -> list[Detection]: ...


class EmbeddingCipher(Protocol):
    def protect(self, data: bytes) -> bytes: ...
    def unprotect(self, data: bytes) -> bytes: ...


class GalleryStore(Protocol):
    @property
    def revision(self) -> int: ...
    def snapshot(self) -> tuple[int, list[EnrollmentSample]]: ...
    def identities(self) -> list[Identity]: ...
    def put_identity(self, identity: Identity) -> None: ...
    def put_sample(self, sample: EnrollmentSample) -> None: ...
    def delete_sample(self, sample_id: str) -> None: ...
    def delete_identity(self, identity_id: str) -> None: ...
